_BASE_: ../DVIS_Offline_R50_720p.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "./weights/DVIS_offline_ovis_swinl_720p.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
SOLVER:
  IMS_PER_BATCH: 2
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 720

  # For pseudo videos
  PSEUDO:
    MAX_SIZE_TRAIN: 1333
    MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
DATASETS:
  DATASET_RATIO: [1.0, ]
  DATASET_NEED_MAP: [False, ]
  DATASET_TYPE: ['video_instance', ]
  DATASET_TYPE_TEST: ['video_instance', ]
  # The categories of all datasets will be mapped to the categories of the last dataset
  TRAIN: ("ovis_train", )
  TEST: ("ovis_val",)

OUTPUT_DIR: './output_OVIS/2'