_BASE_: DVIS_Online_R50.yaml

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 720

  # For pseudo videos
  PSEUDO:
    MAX_SIZE_TRAIN: 1333
    MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)

OUTPUT_DIR: './output_DVIS_Online_R50_720p_OVIS'